# Generated by Django 3.0.6 on 2020-05-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0002_auto_20200530_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='adress',
            new_name='address',
        ),
    ]
